// Array waar de landen van de newsAPI in staan met daarachter de afkorting die gebruikt wordt
const ISO_a2 = [
    ["United States of America", "us"],
    ["United Arab Emirates", "ae"],
    ["Argentina", "ar"],
    ["Australia", "au"],
    ["Austria", "at"],
    ["Belgium", "be"],
    ["Bulgaria", "bg"],
    ["Brazil", "br"],
    ["Canada", "ca"],
    ["Switzerland", "ch"],
    ["China", "cn"],
    ["Colombia", "co"],
    ["Cuba", "cu"],
    ["Czech Republic", "cz"],
    ["Germany", "de"],
    ["Egypt", "eg"],
    ["France", "fr"],
    ["United Kingdom", "gb"],
    ["Greece", "gr"],
    ["Hong Kong S.A.R.", "hk"],
    ["Hungary", "hu"],
    ["Indonesia", "id"],
    ["India", "in"],
    ["Ireland", "ie"],
    ["Israel", "il"],
    ["Italy", "it"],
    ["Japan", "jp"],
    ["South Korea", "kr"],
    ["Lithuania", "lt"],
    ["Latvia", "lv"],
    ["Morocco", "ma"],
    ["Mexico", "mx"],
    ["Malaysia", "my"],
    ["Nigeria", "ng"],
    ["Netherlands", "nl"],
    ["Norway", "no"],
    ["New Zealand", "nz"],
    ["Philippines", "ph"],
    ["Poland", "pl"],
    ["Portugal", "pt"],
    ["Romania", "ro"],
    ["Russia", "ru"],
    ["Saudi Arabia", "sa"],
    ["Singapore", "sg"],
    ["Republic of Serbia", "rs"],
    ["Slovakia", "sk"],
    ["Slovenia", "si"],
    ["Sweden", "se"],
    ["Thailand", "th"],
    ["Turkey", "tr"],
    ["Taiwan", "tw"],
    ["Ukraine", "ua"],
    ["Venezuela", "ve"],
    ["South Africa", "za"]
]